### ISSUE TITLE
no sql error shown when stored proc update fails

### ISSUE THREAD

**Issue by timabell** [timabell/sqlHawk#37]
get a stack trace but need the error thrown by the server

Updating existing database...
java.lang.Exception: Error updating proc myproc1
        at uk.co.timwise.sqlhawk.db.write.DbWriter.write(DbWriter.java:70)
        at uk.co.timwise.sqlhawk.SchemaMapper.writeDb(SchemaMapper.java:195)
        at uk.co.timwise.sqlhawk.SchemaMapper.RunMapping(SchemaMapper.java:102)
        at uk.co.timwise.sqlhawk.Main.main(Main.java:55)
Caused by: java.sql.SQLException: Invalid column name 'SendToGpc'.
        at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:368)
        at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2820)
        at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2258)
        at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:632)
        at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:584)
        at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:546)
        at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:558)
        at uk.co.timwise.sqlhawk.db.write.DbWriter.write(DbWriter.java:67)
        ... 3 more

**Comment by timabell** [comment]
clearly I'm an idiot. looking further down the stack trace reveals the error
"Caused by: java.sql.SQLException: Invalid column name 'SendToGpc'."
