### ISSUE TITLE
hint to user to run initialize when select fails

### ISSUE THREAD

**Issue by timabell** [timabell/sqlHawk#39]
java.lang.Exception: SELECT FROM SqlHawk_UpgradeLog failed.
        at uk.co.timwise.sqlhawk.db.write.DbWriter.runScriptDirectory(DbWriter.java:214)
        at uk.co.timwise.sqlhawk.db.write.DbWriter.runUpgradeScripts(DbWriter.java:151)
        at uk.co.timwise.sqlhawk.SchemaMapper.writeDb(SchemaMapper.java:212)
        at uk.co.timwise.sqlhawk.SchemaMapper.RunMapping(SchemaMapper.java:106)
        at uk.co.timwise.sqlhawk.Main.main(Main.java:55)
Caused by: java.sql.SQLException: Invalid object name 'SqlHawk_UpgradeLog'.
        at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:368)
        at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2820)
        at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2258)
        at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:632)
        at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:584)
        at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:546)
        at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:558)
        at uk.co.timwise.sqlhawk.db.write.DbWriter.runScriptDirectory(DbWriter.java:206)
        ... 4 more

should read "Reading table SqlHawk_UpgradeLog failed, run with --initialize-tracking before attempting first scripted upgrade"

**Comment by timabell** [comment]
fix committed
