### ISSUE TITLE
html - null pointer exception

### ISSUE THREAD

**Issue by timabell** [timabell/sqlHawk#70]
sqlHawk release-0.7.3 2012-06-06 18:44:25 +0100
More information at http://timabell.github.com/sqlHawk/
License: GPLv3.

10:38:34.046 INFO:    SchemaMapper.getConnection - Connected to Microsoft SQL Server - 10.50.1600
10:38:34.057 INFO:    SchemaMapper.readDb - Gathering schema details...
10:38:34.562 INFO:    HtmlWriter.writeHtml - Gathered schema details
10:38:34.562 INFO:    HtmlWriter.writeHtml - Writing/graphing summary...
java.lang.NullPointerException: charsetName
        at java.io.OutputStreamWriter.<init>(Unknown Source)
        at uk.co.timwise.sqlhawk.util.LineWriter.<init>(LineWriter.java:53)
        at uk.co.timwise.sqlhawk.util.LineWriter.<init>(LineWriter.java:45)
        at uk.co.timwise.sqlhawk.html.HtmlWriter.writeHtml(HtmlWriter.java:117)
        at uk.co.timwise.sqlhawk.controller.SchemaMapper.RunMapping(SchemaMapper.java:94)
        at uk.co.timwise.sqlhawk.console.Main.main(Main.java:49)

**Comment by timabell** [comment]
works with sqlhawk-release-0.7.1.jar

**Comment by timabell** [comment]
fixed but now issue #71 exposed
