### ISSUE TITLE
Null Pointer Exception while Reading Functions

### ISSUE THREAD

**Issue by odelasp** [timabell/sqlHawk#83]
java.lang.NullPointerException
        at uk.co.timwise.sqlhawk.model.Function.<init>(Function.java:42)
        at uk.co.timwise.sqlhawk.db.read.DbReader.initFunctions(DbReader.java:205)
        at uk.co.timwise.sqlhawk.db.read.DbReader.Read(DbReader.java:106)
        at uk.co.timwise.sqlhawk.controller.SchemaMapper.readDb(SchemaMapper.java:152)
        at uk.co.timwise.sqlhawk.controller.SchemaMapper.analyze(SchemaMapper.java:119)
        at uk.co.timwise.sqlhawk.controller.SchemaMapper.RunMapping(SchemaMapper.java:82)
        at uk.co.timwise.sqlhawk.console.Main.main(Main.java:50)

**Comment by odelasp** [comment]
Is there a way we can exclude functions from being read --procedure-exclusion-pattern but let it read the stored procedures?

**Comment by timabell** [comment]
Gosh, a user, hello :-)
I haven't had occasion to look at this project for a long time now, I'm afraid I have no idea off the top of my head. Happy to look at pull requests if you want to contribute.
